### ISSUE TITLE
Fixes errors in range data series

### ISSUE THREAD

**Issue by esloch** [AlertaDengue/AlertaDengue#379]
# Objetivos / Objectivos / Purpose

## Geral / General

* Verify data over 52 weeks

```
web_1            | Traceback (most recent call last):
web_1            |   File "/opt/conda/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
web_1            |     response = get_response(request)
web_1            |   File "/opt/conda/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
web_1            |     response = self.process_exception_by_middleware(e, request)
web_1            |   File "/opt/conda/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
web_1            |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web_1            |   File "/opt/conda/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
web_1            |     return self.dispatch(request, *args, **kwargs)
web_1            |   File "/opt/conda/lib/python3.7/site-packages/django/views/generic/base.py", line 97, in dispatch
web_1            |     return handler(request, *args, **kwargs)
web_1            |   File "/opt/conda/lib/python3.7/site-packages/django/views/generic/base.py", line 158, in get
web_1            |     context = self.get_context_data(**kwargs)
web_1            |   File "/srv/deploy/AlertaDengue/dados/views.py", line 413, in get_context_data
web_1            |     v1 = 0 if not cases_est.size else cases_est[-2]
web_1            | IndexError: index -2 is out of bounds for axis 0 with size 1

```

## Específicos / Specific

>File views.py:

``` 
for d in diseases:
    case_series[d] = dbdata.get_series_by_UF(d, 52)
```

**Comment by esloch** [comment]
Essa issue estará aberta somente até finalizar a nova homepe pois está função não será mais utilizada na views.
