### ISSUE TITLE
Ibis does not recognize the level field

### ISSUE THREAD

**Issue by esloch** [AlertaDengue/AlertaDengue#406]
# Objetivos / Objectivos / Purpose

## Geral / General

* Corrigir erro ao usar somente o modulo datetime como import. (api.views???).
```
import datetime as dt
```
## Específicos / Specific

* traceback
```
Internal Server Error: /report/RJ/202110
Traceback (most recent call last):
  File "/docker-env/miniconda/envs/alertadengue/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/docker-env/miniconda/envs/alertadengue/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/docker-env/miniconda/envs/alertadengue/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/docker-env/miniconda/envs/alertadengue/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/docker-env/miniconda/envs/alertadengue/lib/python3.7/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/docker-env/miniconda/envs/alertadengue/lib/python3.7/site-packages/django/views/generic/base.py", line 158, in get
    context = self.get_context_data(**kwargs)
  File "/work_lab/fiocruz/repositories/AlertaDengue/AlertaDengue/dados/views.py", line 1638, in get_context_data
    regional_names, state, year_week, diseases_key
  File "/work_lab/fiocruz/repositories/AlertaDengue/AlertaDengue/dados/views.py", line 1506, in get_regional_info
    var_climate=var_climate,
  File "/work_lab/fiocruz/repositories/AlertaDengue/AlertaDengue/dados/dbdata.py", line 1674, in read_disease_data
    station_id=station_id,
  File "/work_lab/fiocruz/repositories/AlertaDengue/AlertaDengue/dados/dbdata.py", line 1494, in _get_report_data
    disease, geocodes_list, year_week_start, year_week_end,
  File "/work_lab/fiocruz/repositories/AlertaDengue/AlertaDengue/dados/dbdata.py", line 1366, in _get_hist_disease_expr
    .when((t_hist.nivel.cast('string') == '1'), 'verde')
  File "/docker-env/miniconda/envs/alertadengue/lib/python3.7/site-packages/ibis/expr/types.py", line 459, in __getattr__
    raise AttributeError(key)
AttributeError: nivel
```

**Comment by esloch** [comment]
Resolves in #405.
