### ISSUE TITLE
Poetry build is not working properly

### ISSUE THREAD

**Issue by luabida** [AlertaDengue/AlertaDengue#548]
# Objetivos / Objectivos / Purpose

fix `poetry build`

# Saídas / Salidas / Output

<details>

```
15:17 $ poetry build
Traceback (most recent call last):
  File "/home/luabida/anaconda3/envs/alertadengue-dev/bin/poetry", line 7, in <module>
    from poetry.console import main
  File "/home/luabida/anaconda3/envs/alertadengue-dev/lib/python3.9/site-packages/poetry/console/__init__.py", line 1, in <module>
    from .application import Application
  File "/home/luabida/anaconda3/envs/alertadengue-dev/lib/python3.9/site-packages/poetry/console/application.py", line 7, in <module>
    from .commands.about import AboutCommand
  File "/home/luabida/anaconda3/envs/alertadengue-dev/lib/python3.9/site-packages/poetry/console/commands/__init__.py", line 4, in <module>
    from .check import CheckCommand
  File "/home/luabida/anaconda3/envs/alertadengue-dev/lib/python3.9/site-packages/poetry/console/commands/check.py", line 2, in <module>
    from poetry.factory import Factory
  File "/home/luabida/anaconda3/envs/alertadengue-dev/lib/python3.9/site-packages/poetry/factory.py", line 18, in <module>
    from .repositories.pypi_repository import PyPiRepository
  File "/home/luabida/anaconda3/envs/alertadengue-dev/lib/python3.9/site-packages/poetry/repositories/pypi_repository.py", line 33, in <module>
    from ..inspection.info import PackageInfo
  File "/home/luabida/anaconda3/envs/alertadengue-dev/lib/python3.9/site-packages/poetry/inspection/info.py", line 25, in <module>
    from poetry.utils.env import EnvCommandError
  File "/home/luabida/anaconda3/envs/alertadengue-dev/lib/python3.9/site-packages/poetry/utils/env.py", line 23, in <module>
    import virtualenv
  File "/home/luabida/anaconda3/envs/alertadengue-dev/lib/python3.9/site-packages/virtualenv/__init__.py", line 3, in <module>
    from .run import cli_run, session_via_cli
  File "/home/luabida/anaconda3/envs/alertadengue-dev/lib/python3.9/site-packages/virtualenv/run/__init__.py", line 14, in <module>
    from .plugin.creators import CreatorSelector
  File "/home/luabida/anaconda3/envs/alertadengue-dev/lib/python3.9/site-packages/virtualenv/run/plugin/creators.py", line 6, in <module>
    from virtualenv.create.via_global_ref.builtin.builtin_way import VirtualenvBuiltin
  File "/home/luabida/anaconda3/envs/alertadengue-dev/lib/python3.9/site-packages/virtualenv/create/via_global_ref/builtin/builtin_way.py", line 7, in <module>
    from virtualenv.create.creator import Creator
  File "/home/luabida/anaconda3/envs/alertadengue-dev/lib/python3.9/site-packages/virtualenv/create/creator.py", line 15, in <module>
    from virtualenv.discovery.cached_py_info import LogCmd
  File "/home/luabida/anaconda3/envs/alertadengue-dev/lib/python3.9/site-packages/virtualenv/discovery/cached_py_info.py", line 23, in <module>
    _CACHE[Path(sys.executable)] = PythonInfo()
  File "/home/luabida/anaconda3/envs/alertadengue-dev/lib/python3.9/site-packages/virtualenv/discovery/py_info.py", line 86, in __init__
    self.distutils_install = {u(k): u(v) for k, v in self._distutils_install().items()}
  File "/home/luabida/anaconda3/envs/alertadengue-dev/lib/python3.9/site-packages/virtualenv/discovery/py_info.py", line 152, in _distutils_install
    d = dist.Distribution({"script_args": "--no-user-cfg"})  # conf files not parsed so they do not hijack paths
  File "/home/luabida/anaconda3/envs/alertadengue-dev/lib/python3.9/site-packages/setuptools/dist.py", line 477, in __init__
    _Distribution.__init__(
  File "/home/luabida/anaconda3/envs/alertadengue-dev/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 293, in __init__
    self.finalize_options()
  File "/home/luabida/anaconda3/envs/alertadengue-dev/lib/python3.9/site-packages/setuptools/dist.py", line 901, in finalize_options
    ep(self)
  File "/home/luabida/anaconda3/envs/alertadengue-dev/lib/python3.9/site-packages/setuptools_scm/integration.py", line 100, in infer_version
    config = Configuration.from_file(dist_name=dist_name)
  File "/home/luabida/anaconda3/envs/alertadengue-dev/lib/python3.9/site-packages/setuptools_scm/config.py", line 196, in from_file
    defn = _load_toml(data)
  File "/home/luabida/anaconda3/envs/alertadengue-dev/lib/python3.9/site-packages/setuptools_scm/config.py", line 61, in _lazy_tomli_load
    return loads(data)
  File "/home/luabida/anaconda3/envs/alertadengue-dev/lib/python3.9/site-packages/tomli/_parser.py", line 102, in loads
    pos = key_value_rule(src, pos, out, header, parse_float)
  File "/home/luabida/anaconda3/envs/alertadengue-dev/lib/python3.9/site-packages/tomli/_parser.py", line 326, in key_value_rule
    pos, key, value = parse_key_value_pair(src, pos, parse_float)
  File "/home/luabida/anaconda3/envs/alertadengue-dev/lib/python3.9/site-packages/tomli/_parser.py", line 366, in parse_key_value_pair
    raise suffixed_err(src, pos, "Expected '=' after a key in a key/value pair")
tomli.TOMLDecodeError: Expected '=' after a key in a key/value pair (at line 8, column 8)
```

</details>

**Comment by esloch** [comment]
[Done!](https://github.com/AlertaDengue/AlertaDengue/pull/558/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R8)
Thank you @luabida.
