### ISSUE TITLE
(PostgreSQL): deadlock detected

### ISSUE THREAD

**Issue by esloch** [AlertaDengue/AlertaDengue#555]
#### Specific:  

Other process competing for the same resource in the transaction.

#### Traceback:
``` 
^[[36mweb_1        |^[[0m Task dbf.tasks.import_dbf_to_database[fc9bb9dd-c5cc-44f8-8708-5842a6621a0d] raised unexpected: DeadlockDetected('deadlock detected\nDETAIL:  Process 51305 waits for ShareLock on transaction 196410021; blocked by process 26458.\nProcess 26458 waits for ShareLock on transaction 196410020; blocked by process 51305.\nHINT:  See server log for query details.\nCONTEXT:  while inserting index tuple (271491,71) in relation "Notificacao"\n')
^[[36mweb_1        |^[[0m Traceback (most recent call last):
^[[36mweb_1        |^[[0m   File "/opt/conda/envs/alertadengue/lib/python3.9/site-packages/celery/app/trace.py", line 451, in trace_task
^[[36mweb_1        |^[[0m     R = retval = fun(*args, **kwargs)
^[[36mweb_1        |^[[0m   File "/opt/services/AlertaDengue/dbf/tasks.py", line 68, in import_dbf_to_database
^[[36mweb_1        |^[[0m     sinan.save_to_pgsql()
^[[36mweb_1        |^[[0m   File "/opt/services/AlertaDengue/dbf/sinan.py", line 208, in save_to_pgsql
^[[36mweb_1        |^[[0m     cursor.execute(insert_sql, row)
^[[36mweb_1        |^[[0m   File "/opt/conda/envs/alertadengue/lib/python3.9/site-packages/psycopg2/extras.py", line 146, in execute
^[[36mweb_1        |^[[0m     return super().execute(query, vars)
^[[36mweb_1        |^[[0m psycopg2.errors.DeadlockDetected: deadlock detected
^[[36mweb_1        |^[[0m DETAIL:  Process 51305 waits for ShareLock on transaction 196410021; blocked by process 26458.
^[[36mweb_1        |^[[0m Process 26458 waits for ShareLock on transaction 196410020; blocked by process 51305.
^[[36mweb_1        |^[[0m HINT:  See server log for query details.
^[[36mweb_1        |^[[0m CONTEXT:  while inserting index tuple (271491,71) in relation "Notificacao"
```
#### Possible solution:
https://www.postgresql.org/docs/current/explicit-locking.html#LOCKING-DEADLOCKS

**Comment by fccoelho** [comment]
Maybe you can put your transaction in a queue and put the insert within a `try/ except psycopg2.errors.DeadlockDetected`
if if fails you just push that transaction to the end of the queue to be repeated later.
https://stackoverflow.com/questions/57864644/how-to-avoid-deadlock-in-postgresql

**Comment by luabida** [comment]
Closing as not followed. Can be reopened if necessary
