### ISSUE TITLE
Error sending DBF upload confirmation

### ISSUE THREAD

**Issue by esloch** [AlertaDengue/AlertaDengue#564]
# Objetivos / Objectivos / Purpose

## Geral / General

send_mail does not connect to socket
## Específicos / Specific
Traceback:
``` 
Task dbf.tasks.import_dbf_to_database[f1336c60-7680-4df0-afa0-da5b6e14a759] raised unexpected: OSError(99, 'Cannot assign requested address')
Traceback (most recent call last):
  File "/opt/conda/envs/alertadengue/lib/python3.9/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/services/AlertaDengue/dbf/tasks.py", line 69, in import_dbf_to_database
    send_success_email(dbf)
  File "/opt/services/AlertaDengue/dbf/tasks.py", line 31, in send_success_email
    msg.send()
  File "/opt/conda/envs/alertadengue/lib/python3.9/site-packages/django/core/mail/message.py", line 284, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/opt/conda/envs/alertadengue/lib/python3.9/site-packages/django/core/mail/backends/smtp.py", line 102, in send_messages
    new_conn_created = self.open()
  File "/opt/conda/envs/alertadengue/lib/python3.9/site-packages/django/core/mail/backends/smtp.py", line 62, in open
    self.connection = self.connection_class(self.host, self.port, **connection_params)
  File "/opt/conda/envs/alertadengue/lib/python3.9/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/opt/conda/envs/alertadengue/lib/python3.9/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/opt/conda/envs/alertadengue/lib/python3.9/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/opt/conda/envs/alertadengue/lib/python3.9/socket.py", line 844, in create_connection
    raise err
  File "/opt/conda/envs/alertadengue/lib/python3.9/socket.py", line 832, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

```

**Comment by esloch** [comment]
Added SMTP ports 587 and 25 in the firewall on the HETZNER server.
