### ISSUE TITLE
Error when building environment dependencies

### ISSUE THREAD

**Issue by esloch** [AlertaDengue/AlertaDengue#586]
> No module named '_distutils_hack'
https://github.com/conda/conda/issues/11931
``` 
Error processing line 1 of /opt/conda/envs/alertadengue/lib/python3.9/site-packages/distutils-precedence.pth:

  Traceback (most recent call last):
    File "/opt/conda/envs/alertadengue/lib/python3.9/site.py", line 169, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named '_distutils_hack'

Remainder of file ignored

```

**Comment by esloch** [comment]
Done! Adding the Dependency of setuptools.
