### ISSUE TITLE
Error when not finding the data in the epiweek

### ISSUE THREAD

**Issue by esloch** [AlertaDengue/AlertaDengue#624]
# Objetivos / Objectivos / Purpose

*report/state*:

http://127.0.0.1:8000/report/DF/202308

``` 
[28/Feb/2023 16:31:52] "GET /report/DF/state HTTP/1.1" 200 3362
[28/Feb/2023 16:31:53] "GET /report/DF/202308 HTTP/1.1" 200 3953
Internal Server Error: /fetchdata/DF/53001/202308
Traceback (most recent call last):
  File "/workspace/virtualenv/mambaforge/envs/alertadengue/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/workspace/virtualenv/mambaforge/envs/alertadengue/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/workspace/virtualenv/mambaforge/envs/alertadengue/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/workspace/virtualenv/mambaforge/envs/alertadengue/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/workspace/virtualenv/mambaforge/envs/alertadengue/lib/python3.9/site-packages/django/views/generic/base.py", line 159, in get
    context = self.get_context_data(**kwargs)
  File "/workspace/repos/infodengue/AlertaDengue/AlertaDengue/dados/views.py", line 1124, in get_context_data
    level_chart[d] = ReportStateCharts.create_level_chart(
  File "/workspace/repos/infodengue/AlertaDengue/AlertaDengue/dados/charts/states.py", line 156, in create_level_chart
    df_nivel.nivel = df_nivel.nivel.apply(
  File "/workspace/virtualenv/mambaforge/envs/alertadengue/lib/python3.9/site-packages/pandas/core/series.py", line 4430, in apply
    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()
  File "/workspace/virtualenv/mambaforge/envs/alertadengue/lib/python3.9/site-packages/pandas/core/apply.py", line 1072, in apply
    return self.apply_empty_result()
  File "/workspace/virtualenv/mambaforge/envs/alertadengue/lib/python3.9/site-packages/pandas/core/apply.py", line 1114, in apply_empty_result
    return obj._constructor(dtype=obj.dtype, index=obj.index).__finalize__(
  File "/workspace/virtualenv/mambaforge/envs/alertadengue/lib/python3.9/site-packages/pandas/core/series.py", line 418, in __init__
    data, index = self._init_dict(data, index, dtype)
  File "/workspace/virtualenv/mambaforge/envs/alertadengue/lib/python3.9/site-packages/pandas/core/series.py", line 507, in _init_dict
    s = create_series_with_explicit_dtype(
  File "/workspace/virtualenv/mambaforge/envs/alertadengue/lib/python3.9/site-packages/pandas/core/construction.py", line 856, in create_series_with_explicit_dtype
    return Series(
  File "/workspace/virtualenv/mambaforge/envs/alertadengue/lib/python3.9/site-packages/pandas/core/series.py", line 452, in __init__
    data = sanitize_array(data, index, dtype, copy)
  File "/workspace/virtualenv/mambaforge/envs/alertadengue/lib/python3.9/site-packages/pandas/core/construction.py", line 525, in sanitize_array
    data = construct_1d_arraylike_from_scalar(data, len(index), dtype)
  File "/workspace/virtualenv/mambaforge/envs/alertadengue/lib/python3.9/site-packages/pandas/core/dtypes/cast.py", line 1917, in construct_1d_arraylike_from_scalar
    subarr.fill(value)
ValueError: cannot convert float NaN to integer
```

**Comment by claudia-codeco** [comment]
será que esse issue ainda é válido?
