### ISSUE TITLE
The sync_geofiles command is not generating the json files

### ISSUE THREAD

**Issue by esloch** [AlertaDengue/AlertaDengue#625]
# Objetivos / Objectivos / Purpose

``` 
$ python AlertaDengue/manage.py sync_geofiles
```  
### Traceback:
``` 
13:42 $ python AlertaDengue/manage.py sync_geofiles
Successfully geojson 2206506 synchronized!
Traceback (most recent call last):
  File "/workspace/repos/infodengue/AlertaDengue/AlertaDengue/manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/workspace/virtualenv/mambaforge/envs/alertadengue/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/workspace/virtualenv/mambaforge/envs/alertadengue/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/workspace/virtualenv/mambaforge/envs/alertadengue/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/workspace/virtualenv/mambaforge/envs/alertadengue/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/workspace/repos/infodengue/AlertaDengue/AlertaDengue/gis/management/commands/sync_geofiles.py", line 210, in handle
    self.simplify_geojson(path_root, geocode)
  File "/workspace/repos/infodengue/AlertaDengue/AlertaDengue/gis/management/commands/sync_geofiles.py", line 116, in simplify_geojson
    json.dump(geojson_content, f)
  File "/workspace/virtualenv/mambaforge/envs/alertadengue/lib/python3.9/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/workspace/virtualenv/mambaforge/envs/alertadengue/lib/python3.9/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/workspace/virtualenv/mambaforge/envs/alertadengue/lib/python3.9/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/workspace/virtualenv/mambaforge/envs/alertadengue/lib/python3.9/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/workspace/virtualenv/mambaforge/envs/alertadengue/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Properties is not JSON serializable
``` 

### Debug:
``` 
(Pdb) n
> /workspace/repos/infodengue/AlertaDengue/AlertaDengue/gis/management/commands/sync_geofiles.py(116)simplify_geojson()
-> json.dump(geojson_content, f)
(Pdb) p geojson_content
{'type': 'Feature', 'id': '2206506', 'properties': <fiona.model.Properties object at 0x7f7d56038d90>, 'geometry': {'type': 'Polygon', 'coordinates': (((-41.088139, -6.873552), (-41.095359, -6.756693), (-40.981491, -6.772304), (-40.985822, -6.989759), (-41.001104, -7.088842), (-41.066173, -7.069801), (-41.103299, -7.124276), (-41.080857, -6.997474), (-41.088139, -6.873552)),)}}
(Pdb) n
TypeError: Object of type Properties is not JSON serializable
> /workspace/repos/infodengue/AlertaDengue/AlertaDengue/gis/management/commands/sync_geofiles.py(116)simplify_geojson()
-> json.dump(geojson_content, f)
```

**Comment by esloch** [comment]
Done!
