### ISSUE TITLE
Error: 'Connection' object has no attribute 'cursor'

### ISSUE THREAD

**Issue by esloch** [AlertaDengue/AlertaDengue#698]
**Description:**
While executing the `count_cities_by_uf` method in the `dados/dbdata.py` module, an `AttributeError` is raised, indicating that the 'Connection' object has no attribute 'cursor'. This issue is occurring in the `read_sql` function from the `pandas.io.sql` module.

**Steps to Reproduce:**
1. Trigger the execution of the `count_cities_by_uf` method with appropriate arguments (state_name, disease) in the given context.

**Traceback**
```
Traceback (most recent call last):
  File "/opt/conda/envs/alertadengue/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/conda/envs/alertadengue/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/conda/envs/alertadengue/lib/python3.10/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/opt/conda/envs/alertadengue/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/conda/envs/alertadengue/lib/python3.10/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/conda/envs/alertadengue/lib/python3.10/site-packages/django/views/generic/base.py", line 159, in get
    context = self.get_context_data(**kwargs)
  File "/opt/services/AlertaDengue/dados/views.py", line 577, in get_context_data
    ] = notif_resume.count_cities_by_uf(state_name, disease)
  File "/opt/services/AlertaDengue/dados/dbdata.py", line 664, in count_cities_by_uf
    return pd.read_sql(sql, conn).astype(int).iloc[0]["count"]
  File "/opt/conda/envs/alertadengue/lib/python3.10/site-packages/pandas/io/sql.py", line 706, in read_sql
    return pandas_sql.read_query(
  File "/opt/conda/envs/alertadengue/lib/python3.10/site-packages/pandas/io/sql.py", line 2739, in read_query
    cursor = self.execute(sql, params)
  File "/opt/conda/envs/alertadengue/lib/python3.10/site-packages/pandas/io/sql.py", line 2673, in execute
    cur = self.con.cursor()
AttributeError: 'Connection' object has no attribute 'cursor'
```  

**Expected Behavior:**
The `read_sql` function should handle the connection object correctly, and the cursor attribute should be accessible. The data retrieval operation from the database should proceed without raising an AttributeError.

**Actual Behavior:**
The AttributeError is raised at line 664 in `dados/dbdata.py`, preventing the execution of the `count_cities_by_uf` method. The cursor attribute is not recognized on the 'Connection' object.

**Comment by luabida** [comment]
I've the same issue, updating SQLAlchemy to last version should be enough
